#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset



if [ "${DATABASE_USER}" ]; then

  python << END
import sys
import time

import psycopg2

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        psycopg2.connect(
            dbname="${DATABASE_NAME}",
            user="${DATABASE_USER}",
            password="${DATABASE_PASSWORD}",
            host="${DATABASE_HOST}",
            port="${DATABASE_PORT}",
        )
        break
    except psycopg2.OperationalError as error:
        sys.stderr.write("Waiting for PostgreSQL to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))

    time.sleep(1)
END

fi

>&2 echo 'Database is available'

exec "$@"
